dist: trusty
sudo: true

language: node_js
node_js:
- "8.12.0"

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable


install:
- npm install

script:
- npm run test
