version: 2
jobs:
  build:
    working_directory: ~/flightSearch
    docker:
    - image: circleci/node:8-browsers
    steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
    - run: npm install
    - save_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
        paths:
        - "node_modules"
    - run: npm run test
    - run:
        name: code-coverage
        command: './node_modules/.bin/nyc report --reporter=text-lcov'
    - store_artifacts:
        path: test-results.xml
        prefix: tests
    - store_artifacts:
        path: coverage
        prefix: coverage
    - store_test_results:
        path: test-results.xml
