version: 2
jobs:
  build:
    working_directory: ~/flightSearch
    docker:
    - image: circleci/node:8-browsers
    steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
    - run: npm install
    - save_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
        paths:
        - "node_modules"
    - run: npm run test --watch=false
